# Generated by Django 2.2.5 on 2019-09-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_auto_20190916_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categoryname',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='priority',
            new_name='priorityname',
        ),
    ]
