# Generated by Django 2.2.5 on 2019-09-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0003_auto_20190917_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='isStarred',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.DateField(),
        ),
    ]
