# Generated by Django 2.2.5 on 2019-09-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0004_auto_20190917_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
